// packages/main-react/src/layout/LayoutNav/index.tsx
import React from 'react';
import { Menu } from 'antd';
import type { MenuProps } from 'antd';

const LayoutNav: React.FC = () => {
  let activeIndex = window.location.pathname;

  const handleClick: MenuProps['onClick'] = (e) => {
    activeIndex = e.key;
    window.location.href = e.key;
  };

  const items = [
    { label: 'vue HomePage1', key: '/micro-vue/HomePage1' },
    { label: 'vue HomePage2', key: '/micro-vue/HomePage2' },
    { label: 'react HomePage1', key: '/micro-react/HomePage1' },
    { label: 'react HomePage2', key: '/micro-react/HomePage2' },
  ];

  return (
    <nav className="layout-nav">
      <Menu
        defaultSelectedKeys={[activeIndex]}
        items={items}
        onClick={handleClick}
      />
    </nav>
  );
};

export default LayoutNav;

// packages/main-vue/src/layout/LayoutNav.vue
<template>
  <nav class="layout-nav">
    <el-menu :default-active="activeIndex" @select="handleSelect">
      <el-menu-item index="/micro-vue/HomePage1">
        <span>vue HomePage1</span>
      </el-menu-item>
      <el-menu-item index="/micro-vue/HomePage2">
        <span>vue HomePage2</span>
      </el-menu-item>
      <el-menu-item index="/micro-react/HomePage1">
        <span>react HomePage1</span>
      </el-menu-item>
      <el-menu-item index="/micro-react/HomePage2">
        <span>react HomePage2</span>
      </el-menu-item>
    </el-menu>
  </nav>
</template>
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'App',
  setup() {
    let activeIndex = window.location.pathname;
    const handleSelect = (path: string) => {
      activeIndex = path;
      window.location.href = path;
    };

    return {
      activeIndex,
      handleSelect,
    };
  },
});
</script>
